name: Urørte repositories
on:
  workflow_dispatch:
  schedule:
    - cron: '15 8 * * 3'

jobs:
  urorte-repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/teamsykmelding-automations/actions/bunjob@main
        with:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: bun run scripts/ancient-repos.ts
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
