name: Repos med feil i CODEOWNERS
on:
  workflow_dispatch:
  schedule:
    - cron: '45 6 * * 4'
env:
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
jobs:
  codeowner-issues-repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.8.1
      - run: bun install --production
      - run: bun run scripts/codeownerless-repos.ts
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
