name: Repos med feil i CODEOWNERS
on:
  workflow_dispatch:
  schedule:
    - cron: '45 6 * * 4'

jobs:
  codeowner-issues-repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/teamsykmelding-automations/actions/bunjob@main
        with:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: bun run scripts/codeownerless-repos.ts
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
