name: Automatisk oppdatering av distroless digest for frontendapper
on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 1'
env:
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
  DISTROLESS_IMAGE: gcr.io/distroless/nodejs18-debian11
jobs:
  digest-changed:
    name: Fetch new digest for distroless images i frontend repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.8.1
      - run: bun install --production
      - id: new-digest
        run: bun run scripts/update-distroless-digest.ts --has-new-digest --image=${{ env.DISTROLESS_IMAGE }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
    outputs:
      changed: ${{ steps.new-digest.outputs.digest-changed }}
      digest: ${{ steps.new-digest.outputs.digest }}
  approval-for-commits:
    if: ${{ needs.digest-changed.outputs.changed == 'true' }}
    needs: digest-changed
    name: Update Dockerfiles and push to main
    runs-on: ubuntu-latest
    environment:
      name: Distroless frontend
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.8.1
      - run: bun install --production
      - run: bun run scripts/update-distroless-digest.ts --make-changes --image=${{ env.DISTROLESS_IMAGE }} --digest=${{ needs.digest-changed.outputs.digest }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          READER_TOKEN: ${{ secrets.SECURITY_READ_TOKEN }}
