name: Automatisk oppdatering av distroless digest for backendapper
on:
  workflow_dispatch:
  schedule:
    - cron: '45 6 * * 1'
env:
  DISTROLESS_IMAGE: gcr.io/distroless/java17-debian11

jobs:
  digest-changed:
    name: Fetch new digest for distroless images i backend repos
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/teamsykmelding-automations/actions/bunjob@main
        with:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - id: new-digest
        run: bun run scripts/update-distroless-digest.ts --has-new-digest --image=${{ env.DISTROLESS_IMAGE }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
    outputs:
      changed: ${{ steps.new-digest.outputs.digest-changed }}
      digest: ${{ steps.new-digest.outputs.digest }}
  approval-for-commits:
    if: ${{ needs.digest-changed.outputs.changed == 'true' }}
    needs: digest-changed
    name: Update Dockerfiles and push to main
    runs-on: ubuntu-latest
    environment:
      name: Distroless backend
    steps:
      - uses: navikt/teamsykmelding-automations/actions/bunjob@main
      - run: bun run scripts/update-distroless-digest.ts --make-changes --image=${{ env.DISTROLESS_IMAGE }} --digest=${{ needs.digest-changed.outputs.digest }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          READER_TOKEN: ${{ secrets.SECURITY_READ_TOKEN }}
