name: Sjekk sårbarheter ukentlig for MODERATE og LOW
on:
  workflow_dispatch:
  schedule:
    - cron: '10 10 * * 5'
env:
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
jobs:
  sarbarheter-ukentlig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: bun run scripts/risks.ts --levels=LOW,MODERATE
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
