name: Sjekk sårbarheter daglig for CRITICAL og HIGH
on:
  workflow_dispatch:
  schedule:
    - cron: '03 07 * * *'

jobs:
  sarbarheter-daglig:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/teamsykmelding-automations/actions/bunjob@main
        with:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: bun run scripts/risks.ts --levels=HIGH,CRITICAL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          READER_TOKEN: ${{ secrets.SECURITY_READ_TOKEN }}
