name: Sjekk sårbarheter ukentlig for MODERATE og LOW
on:
  workflow_dispatch:
  schedule:
    - cron: '10 10 * * 5'

jobs:
  sarbarheter-ukentlig:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/teamsykmelding-automations/actions/bunjob@main
        with:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: bun run scripts/risks.ts --levels=LOW,MODERATE
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          READER_TOKEN: ${{ secrets.SECURITY_READ_TOKEN }}
